# ENTER URL TO DOWNLOAD FROM
GOOGLE_FILE = ''

# ENTER THE BING IP ADDRESS TO UPLOAD TO
BING_IP_ADDRESS = ''

# ENTER THE BING FTP USERNAME
BING_FTP_USERNAME = '' 

# ENTER THE BING FTP PASSWORD
BING_FTP_PASSWORD = '' 
